#ifndef PARSERDEF_H
#define PARSERDEF_H
struct ParserDef{
    enum errcode { SUCCESS=0,GRAMMAR_NOTFOUND=-1,GRAMMAR_ERROR=-2,INPUTTEST_NOTFOUND=-3,PARSE_ERROR=-4,SERVER_LISTEN_ERROR=-5  };
    
};
#endif // PARSERDEF_H

